<?php

define(ISLANDORA_OBJECT_LOCK_REST_MENU, MENU_ISLANDORA_REST_OBJECT . '/%/lock');

function islandora_object_lock_rest_menu() {
  $items = array();
  $item[ISLANDORA_OBJECT_LOCK_REST_MENU] = array(
    'page callback' => 'islandora_object_lock_rest_callback',
    'page arguments' => array(4),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function islandora_object_lock_rest_callback($pid) {
  module_load_include('inc', 'islandora_rest', 'includes/utilities');
  $method = islandora_rest_get_request_method();

  switch ($method) {
    case 'GET':
      islandora_object_lock_rest_get($pid);
      break;
  }
}

function islandora_object_lock_rest_get($pid) {
  $object = islandora_object_load($pid);
  $locked = islandora_object_lock_is_locked($object);
}